// overall rating would help figure out the monster toughness

export let monsters = [
  {
    name: 'Goblin',
    attack: 5,
    defence: 5,
    strength: 5,
    agility: 2300,
    abilities: [],
    elements: [],
    magic: 0,
    weapon: 1,
    armour: 1,
    life: 50,
    stamina: 100,
    count: 0,
  },
  {
    name: 'Wolf',
    attack: 5,
    defence: 3,
    strength: 4,
    agility: 2000,
    abilities: [],
    elements: [],
    magic: 0,
    weapon: 1,
    armour: 1,
    life: 55,
    stamina: 100,
    count: 0,
  },
  {
    name: 'Troll',
    attack: 6,
    defence: 6,
    strength: 7,
    agility: 2500,
    abilities: [],
    elements: [],
    magic: 0,
    weapon: 1,
    armour: 1,
    life: 60,
    stamina: 70,
    count: 0,
  },
  {
    name: 'Dark Elf',
    attack: 6,
    defence: 5,
    strength: 4,
    agility: 2000,
    weapon: 1.2,
    armour: 1,
    magic: 0,
    abilities: [],
    element: ['fire'],
    life: 70,
    stamina: 100,
    count: 0,
  },
  {
    name: 'BOSS - Ork',
    attack: 7,
    defence: 8,
    strength: 8,
    agility: 2100,
    abilities: [], // TODO need some abilities here
    magic: 0,
    weapon: 1.1,
    armour: 1.1,
    life: 100,
    stamina: 70,
    count: 0,
  },
  {
    name: 'Bear',
    attack: 8,
    defence: 6,
    strength: 11,
    agility: 2300,
    abilities: [],
    magic: 0,
    weapon: 1,
    armour: 1,
    life: 65,
    stamina: 100,
    count: 0,
  },

  {
    name: 'Ice Witch',
    attack: 8,
    defence: 7,
    strength: 6,
    agility: 2300,
    abilities: [], // TODO need some magic here, high magic could resist this?
    magic: 0,
    elements: ['ice'],
    weapon: 1.1,
    armour: 1.1,
    life: 80,
    stamina: 80,
    count: 0,
  },
  {
    name: 'Chimera',
    attack: 8,
    defence: 6,
    strength: 6,
    agility: 2000,
    abilities: [],
    magic: 0,
    weapon: 1.1,
    armour: 1.1,
    life: 80,
    stamina: 80,
    count: 0,
  },
  {
    name: 'Fire Witch',
    attack: 7,
    defence: 6,
    strength: 6,
    agility: 2300,
    abilities: [],
    magic: 0,
    weapon: 1.1,
    armour: 1.1,
    life: 65,
    stamina: 80,
    count: 0,
  },
  {
    name: 'BOSS - Adorable snowman',
    attack: 7,
    defence: 6,
    strength: 6,
    agility: 2300,
    abilities: [],
    magic: 0,
    weapon: 1.1,
    armour: 1.1,
    life: 100,
    stamina: 80,
    count: 0,
  },
]
