// overall rating would help figure out the monster toughness

export let monsters = [
  {
    name: 'Goblin',
    attack: 5,
    defence: 5,
    strength: 5,
    agility: 2300,
    abilities: [],
    weapon: 1,
    armour: 1,
    life: 50,
    stamina: 100,
    count: 0,
  },
  {
    name: 'Wolf',
    attack: 5,
    defence: 3,
    strength: 4,
    agility: 2000,
    weapon: 1,
    armour: 1,
    life: 55,
    stamina: 100,
    count: 0,
  },
  {
    name: 'Troll',
    attack: 6,
    defence: 6,
    strength: 7,
    agility: 2500,
    weapon: 1,
    armour: 1,
    life: 60,
    stamina: 70,
    count: 0,
  },
  {
    name: 'Dark Elf',
    attack: 6,
    defence: 5,
    strength: 4,
    agility: 2000,
    weapon: 1.2,
    armour: 1,
    life: 60,
    stamina: 100,
    count: 0,
  },
  {
    name: 'Ork',
    attack: 7,
    defence: 6,
    strength: 6,
    agility: 2300,
    weapon: 1.1,
    armour: 1.1,
    life: 65,
    stamina: 80,
    count: 0,
  },
]
